snowdbt:
  outputs:
    dev:
      account: FFSXKZG-WZ34394
      database: snowdbt
      password: rzBSDe6zfkuzRnp
      role: ACCOUNTADMIN
      schema: source
      threads: 8
      type: snowflake
      user: maneeshsnf
      warehouse: COMPUTE_WH
  target: dev
