snowdbt:
  outputs:
    dev:
      account: BTYQGLQ-WR38891
      database: sdbt
      password: yXdLVhDNC6H8pSv
      role: ACCOUNTADMIN
      schema: staging
      threads: 8
      type: snowflake
      user: Rahul123
      warehouse: COMPUTE_WH
  target: dev
